name: Create New Release Branch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes to the repo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all branches are fetched

      - name: Get Latest Release Branch
        id: get-latest-release
        run: |
          latest_release=$(git branch -r | grep -o 'release-[0-9]\+' | sort -V | tail -n 1)
          if [ -z "$latest_release" ]; then
            new_number=1
          else
            latest_number=$(echo "$latest_release" | grep -o '[0-9]\+$')
            new_number=$((latest_number + 1))
          fi
          new_release="release-$new_number"
          echo "NEW_RELEASE=$new_release" >> $GITHUB_ENV
          echo "New release branch: $new_release"

      - name: Create and Push New Release Branch
        run: |
          git checkout -b "$NEW_RELEASE"
          git push origin "$NEW_RELEASE"

      - name: Update deploy.yml in New Release Branch
        run: |
          git checkout "$NEW_RELEASE"
          echo "Before update:"
          cat .github/workflows/deploy.yml

          # Replace old release branch name with the new one
          sed -i -E "s/release-[0-9]+/release-$new_number/g" .github/workflows/deploy.yml

          echo "After update:"
          cat .github/workflows/deploy.yml

          # Commit and push changes if any
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git diff --quiet || (git commit -am "Update deploy.yml to track $NEW_RELEASE" && git push origin "$NEW_RELEASE")
