name: Create New Release Branch

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes to the repo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all branches are fetched

      - name: Get Latest Release Branch
        id: get-latest-release
        run: |
          latest_release=$(git branch -r | grep -o 'release-[0-9]\+' | sort -V | tail -n 1)
          if [ -z "$latest_release" ]; then
            new_release="release-1"
          else
            latest_number=$(echo "$latest_release" | grep -o '[0-9]\+$')
            new_number=$((latest_number + 1))
            new_release="release-$new_number"
          fi
          echo "NEW_RELEASE=$new_release" >> $GITHUB_ENV
          echo "New release branch: $new_release"

      - name: Update deploy.yml in Main Branch
        run: |
          git checkout main
          git pull origin main
          sed -i -E "s/(branches:\s*- release-)[0-9]+/\1$NEW_RELEASE/" .github/workflows/deploy.yml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git diff --quiet || (git commit -am "Update deploy.yml to track $NEW_RELEASE" && git push origin main)


      - name: Create and Push New Release Branch
        run: |
          git checkout -b "$NEW_RELEASE"
          git push origin "$NEW_RELEASE"

